require('settings')
require('mappings')
require('modules.customline')
require('colorschemes-config.simpleblack')
require('packer-config')
require('treesitter-config')
require('lsp-config')
require('cmp-config')
